### ISSUE TITLE
Change of tool mode not displaying

### ISSUE THREAD

**Issue by Gokuofuin** [VoidArkMods/QoLPlus#6] opened 2023-11-18 09:31 UTC
Hi there

When i change the tool mode of say the multi-tool then I don't see any indication of what mode its on. Is this a bug or is it a setting?

**Comment by VoidArkMods** [comment] 2023-11-18 11:39
Hello!

It is a bug: the model that the MultiTool is using changed when moving to ASA and it is not able to display the currently selected sub-mode anymore.

**Comment by klitzkedakota** [comment] 2023-11-18 19:30
If I may make a suggestion, until the problem is solved of displaying mode on the weapon.... Add a "sub" radial wheel to further select tool settings. Similar to radial wheel for Dinos, click behavior and more options appear in a sub-radial wheel. On multitool, could be to select Dino, then open a sub-radial wheel to select from Kill, spay, chibify, mating, etc..

**Comment by VoidArkMods** [comment] 2023-11-24 19:50
Fixed as part of CurseForge release 12.

**Closed by VoidArkMods** 2023-11-24 19:50 UTC
