### ISSUE TITLE
Propagator broken

### ISSUE THREAD

**Issue by KeikoDana** [VoidArkMods/QoLPlus#153] opened 2024-01-28 05:24 UTC
Hello,

We have a serious problem with the propagator.

Basically, in the beginning, we have any problems with the stat stacking, with all the dinos in ASA. But since ten days (approximately), we can't have stats accumulations anymore. For exemple, our T-Rex with 73 in dommage can't get up anymore. He's stay  blocked in this level off stat. However the new stat after the use of propagator must be 77 (73+4 with 2 impulsions).

We have use the mutator for forced the mutations with two impulsions, then we used the propagator for forced the stat stacking for dommage 73 to dommage 77. But the propagator don't take into account the real stat in the cryopod, he doesn't recognise the real stat oif the T-Rex (or other dino).

What can we do ? We think it's a problem with the mod because all people in our server have the same thing.

Other problem : the propagator crash after use : he didn't stop when we selection "stop breeding" after use. We must withdraw the structure and to place on the ground anew. It's consumes more elements than necessary/initially intented.
In the beginning, we don't have this problem and that is arrived in the same time than the previous problem (so 10 day before).

Thanks in advence for helping me with this.

**Comment by VoidArkMods** [comment] 2024-01-28 10:25
Hello!
This is a duplicate of https://github.com/VoidArkMods/QoLPlus/issues/149, I'll close it as "Duplicate", but a temporary fix is on its way for the forwarding of mutations.
Regarding the issue where the propagator can't be stopped, a few users reported it in another issue, but I haven't figured out a way of reproducing it on my side yet. Plus, even though it costs slightly more element, replacing it is a temporary workaround (even though it's not ideal, yes). I'll be investigating further.

**Closed by VoidArkMods** 2024-01-28 10:25 UTC
