### ISSUE TITLE
Propagator Mutations broken

### ISSUE THREAD

**Issue by SvarogTheWiccan** [VoidArkMods/QoLPlus#149] opened 2024-01-23 22:26 UTC
Hello there

After the last patch released mutation system was changed, on an attempt to make it work like ASA the mutation system got broken, it simulates to work like it, but the propagator doesn't recognize the new mutations gotten after this patch to inherit them into the babies.

I have spawned 200 dodos lvl 1.
I'm mating them inside of the propagator until I got a double mutation lvl 5 male.
I'm using that male, I have gotten over 200 eggs, none of the babies has gotten the stats from that male.
Also we are getting speed mutations without being registered on the mutations counter but the base level is increasing.
I did the same with a dino I had mutated before outside of propagator, it has 10 mutations on melee and 10 on HP, I'm using clean females, got 150 eggs and none of them pulled any of the stats from the parent, but I have gotten new mutations.

On my opinion the mutations system was working fine before this patch, I hope it can be rolled back or fixed.
Thanks

**Comment by SvarogTheWiccan** [comment] 2024-01-23 22:58
An easy explanation for this would be that, propagator input system don't recognize mutations in their additive tab, in example 50 (+2) the (+2) gets excluded from the pool to inherit to the babies and it only works with base/wild stats tab.
The output for the babies is working "fine" as they get the mutations on additive tab like the new system in ASA.
This is  not as critical, but we still get mutations in speed or oxygen even when ASA breeding system locks those stats depending on tames, the new UI is hiding speed so we don't see clearly the mutation went there, base level increases proportional to the amount of mutations on speed, but the mutation counter ignores them.

**Comment by axelguerin** [comment] 2024-01-24 10:41
Same for me,
The mutation on baby goes in the muta tab but is not counted for the next reproduction.

**Comment by VoidArkMods** [comment] 2024-01-24 16:04
Hello!
Yes, I've been able to reproduce the issue. Before the update, the mutation were directly added to the wild stat, meaning they were naturally forwarded by taking the wild stat of the parent. But with the mutation stack, there are 3 stacks: the male parent one, the female parent one, and the random new one. Both parents ones are not considered at all, meaning it's always the random mutation that overrides everything. I'll have a look at that and try to fix it ASAP.

**Comment by VoidArkMods** [comment] 2024-01-25 11:12
I am part of the community as well, TiiaAurora is a friend, the video you pasted was already the one I was basing the fix on :D
I'm fairly confident the happy path should work as intended, but there are some concerns about the border-case where both parents have the same wild stat and different mutations: it appears safer on the propagator side to just always go with the higher mutation stack in that case, yet in reality both mutations stack have a chance to be selected.

**Comment by VoidArkMods** [comment] 2024-01-25 11:51
Yes, these are my conclusions as well: I can't see any valid reason to want the lower mutation stack anyway, so it does not appear to be annoying. It's important to know that there are multiple places in the code where the propagator behaves differently than the vanilla breeding process. For example, the vanilla breeding process has a 55% chance to select the higher stat VS 45% for the lower stat, but the propagator always generates a random boolean (so 50%/50%). Therefore, the purpose of the propagator is not to simulate exactly how the vanilla breeding process works, but is rather another interpretation, with similarities and differences. At the light of that, it feels reasonable to allow the propagator to always select the higher mutation stack when both wild level stat are the same.

**Comment by VoidArkMods** [comment] 2024-01-25 12:18
For now, it looks promising:
![image](https://github.com/VoidArkMods/QoLPlus/assets/151264019/953007d9-e61b-49d9-8b7f-73704015cf16)
![image](https://github.com/VoidArkMods/QoLPlus/assets/151264019/9b982eae-8d59-4e51-9001-9814c0a4dba5)

**Comment by VoidArkMods** [comment] 2024-01-25 20:36
The fix has been pushed, tested and is now waiting for review. As in the screenshots, it's not the ideal solution, but it unlocks the situation. Once the cross-platform build is accepted, the fix will be available to everybody after an update.

**Comment by WeWyaha** [comment] 2024-01-27 02:57
Hello yall.the propagator seems to mutated a stat only once and when I bred for second same mutation stat it doesn't work.pls help

**Comment by Roundie74** [comment] 2024-01-27 04:14
> Hello yall.the propagator seems to mutated a stat only once and when I bred for second same mutation stat it doesn't work.pls help

Did you even read the thread before commenting?  The Dev has pushed the fix for review but it hasn't been published yet.  The last publish date for the mod was the 23rd.  The fix was submitted yesterday.

**Comment by VoidArkMods** [comment] 2024-01-28 16:49
The fix has been approved and is now available to everybody.

**Closed by VoidArkMods** 2024-01-28 16:49 UTC
