### ISSUE TITLE
Crossplay?

### ISSUE THREAD

**Issue by Tobeey1993** [VoidArkMods/QoLPlus#75] opened 2023-12-07 07:08 UTC
I haven't read any information. Is the mod crossplay compatible?

**Comment by garrowson** [comment] 2023-12-07 16:03
We have players on Playstation joining the server

**Comment by VoidArkMods** [comment] 2023-12-08 21:41
Hello!
This is a duplicate of a couple other issues already opened by other players. The mod is fully crossplay, I tested all platforms personally. The mod will not drop cross-platform support: it will lead to slower releases (each PS5/Xbox release requires a review that can take up to one week), but I commit on never forcing servers to go back to PC only, even temporarily.

**Closed by VoidArkMods** 2023-12-08 21:41 UTC
