### ISSUE TITLE
Propagator addon

### ISSUE THREAD

**Issue by brothasx** [VoidArkMods/QoLPlus#181] opened 2024-02-19 10:57 UTC
Will Dino Depot be added to the propagator?

I have noticed different QoL mods  has made it possible allready to use the Dino Depot balls. 

So i was wondering why its that hard to add it to this one.
I provided previously allready the information on how to contact the developer of Dino Depot but no response on that matter. 

I loved this mod and the time you putted into it, until you went silent for months and do only changes every few weeks.

Kind regards,

![Screenshot_1](https://github.com/VoidArkMods/QoLPlus/assets/49365370/67d217fb-6a1d-4d2a-a640-1561055740f1)

**Comment by VoidArkMods** [comment] 2024-02-19 11:36
Hello.
Please, avoid opening new issues that are duplicate of other already opened issues, especially when you know it beforehand. The issue tracker is there to centralize the problems and planning accordingly to fix them, it is not a private message system.

Regarding dino depot, I have said everything I had to say on this topic. Anybody can come with a new way of defining how a dino is stored with new custom-made data model. If some effort is put into making an exception for dino depot, then it would also have to be made for all the existing and future mods redefining something already defined by Wildcard multiple years ago when they released extinction. Consider ASE: dino storage v2 back then was enhancing a lot the experience with its soul balls, yet it was compatible out of the box with the propagator. This is because is extended on the building blocks already present, it was not redefining its own standard for storing creatures.
The propagator is a structure that allows breeding through cryopods. Anything that is a cryopod is compatible. If there are some bugs (like the reason pelayoris' cryos were not being detected properly when it comes to the gender), that's on me to fix. But you can't come up and decide that suddently the propagator should be able to breed raw prime meat and manage to understand from which dino it came from.

On a personal note: I bought a computer, an xbox and a ps5 especially to work on this mod. At the beginning it was only for my games on my servers, but I got convinced to make it available to everybody. The goal is not to build a fan base or climb up the curseforge pages, it's just to make it available and for free. If you don't like it anymore, then feel free to find an alternative, there are plenty of mods in the sea. I can't even start the devkit right now. I can't even update windows or my GPU drivers because of this BS of i9 13900kf, and as a result I get this kind of "why does it takes so long?" or "i don't like it anymore" messages in duplicate issues. Thanks a lot, it's very encouraging.

Closed as duplicate.

**Closed as not planned** 2024-02-19 16:40 UTC
